import React from 'react';
import { motion } from 'framer-motion';
import { ExternalLinkIcon, LockIcon, ShieldCheckIcon, ZapIcon } from 'lucide-react';
const FEATURES = [
  { icon: <ZapIcon size={18} />, title: 'Efficient reporting', body: 'A clear, structured form helps mobile patrol staff record every voicemail consistently.' },
  { icon: <ShieldCheckIcon size={18} />, title: 'Organised records', body: 'Entries are grouped by month for quick review and a dependable operational history.' },
  { icon: <LockIcon size={18} />, title: 'Centralised records', body: 'Submitted entries are organised in the authorised Google Drive by month and site, with a local browser copy for quick viewing.' }
];
export function About() { return <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 sm:py-10"><motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="rounded-3xl border border-black/5 bg-white p-7 text-center shadow-card sm:p-10"><img src="/logo-cta.png" alt="SMS Security logo" className="mx-auto h-20 w-20 object-contain" /><h1 className="mt-5 text-3xl font-extrabold tracking-tight text-ink">SMS Security Voicemail Service</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-ink/60">A focused operational tool for recording mobile patrol voicemail details accurately, consistently, and efficiently.</p></motion.section><div className="mt-5 grid gap-4 sm:grid-cols-3">{FEATURES.map((feature) => <section key={feature.title} className="rounded-2xl border border-black/5 bg-white p-5 shadow-card"><div className="mb-3 flex h-9 w-9 items-center justify-center rounded-xl bg-maroon/5 text-maroon">{feature.icon}</div><h2 className="text-sm font-bold text-ink">{feature.title}</h2><p className="mt-1.5 text-xs leading-5 text-ink/55">{feature.body}</p></section>)}</div><section className="mt-5 rounded-3xl bg-maroon p-7 text-white sm:flex sm:items-center sm:justify-between sm:gap-8"><div><p className="text-xs font-bold uppercase tracking-widest text-white/65">About SMS Security</p><h2 className="mt-2 text-xl font-bold">Professional security across Toronto and the GTA</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/75">SMS Security is a locally owned, full-service security provider serving residential, commercial, and industrial properties with professional personnel, mobile patrols, monitoring, and security technology.</p></div><a href="https://smssecurity.ca/" target="_blank" rel="noreferrer" className="mt-5 inline-flex shrink-0 items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-maroon hover:bg-white/90 sm:mt-0">Visit official website <ExternalLinkIcon size={15} /></a></section><p className="mt-6 text-center text-xs leading-5 text-ink/45">This voicemail logging application is an operational tool created by Jagroop Singh. For official company information and services, visit <a className="font-semibold text-maroon hover:underline" href="https://smssecurity.ca/" target="_blank" rel="noreferrer">smssecurity.ca</a>.</p></div>; }
